version: '3.8'

networks:
    EXAMPLE-network:

services:
    db:
        image: mongo:4.2.0
        container_name: EXAMPLE
        networks:
            default:
            EXAMPLE-network:
        volumes:
            - mongo-EXAMPLE:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped

volumes:
    mongo-EXAMPLE:
